disabled_rules:
- trailing_whitespace
- vertical_whitespace_opening_braces
opt_in_rules:
- colon
- empty_count
- empty_string
- force_unwrapping
- type_name
- closure_spacing
- trailing_closure
- vertical_whitespace_opening_braces
- vertical_parameter_alignment_on_call
- unused_import
- unused_declaration
excluded:
- Carthage
- Pods
- SwiftLint/Common/3rdPartyLib
- MindMap/SupportedFiles/R.generated.swift
line_length:
    warning: 150
    error: 200
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true
type_name:
    allowed_symbols: "_"
identifier_name:
  allowed_symbols: "_"
  min_length: 2
  max_length:
    warning: 90
    error: 1000
  excluded:
    - id
function_body_length:
    warning: 300
    error: 500
function_parameter_count:
    warning: 6
    error: 8
type_body_length:
    warning: 300
    error: 500
file_length:
    warning: 500
    error: 1000
    ignore_comment_only_lines: true
cyclomatic_complexity:
    warning: 15
    error: 25
closure_spacing: warning
force_unwrapping: warning
colon: warning
reporter: "xcode"
